### ISSUE TITLE
Alter Welcome Template

### ISSUE THREAD

**Issue by ondoheer** [MasoniteFramework/cli#4]
After running ```craft auth``` the Welcome template ought to show the login menu, it would be more user friendly. I can do it, but am thinking on what the best way to acomplish it would be. I reckon a chek on whether the welcome exists or not before hand? I am assuming people will call the craft auth command as soon as they start the project, but that might no be the case? 

What do you think?

**Comment by josephmancuso** [comment]
umm I don't think we should show the login screen right away. I think we should keep the welcome screen although I do agree there should be a change. How about we add a check in extending a base from the welcome template?

something like:

* if the auth/base.html file exists, extend from that, 
* else just show normal?

What do you think of that?

**Comment by ondoheer** [comment]
I think the first solution is good enough. I'm sorry if I'm focusing on really small simple problems. I just started noticing stuff as I started playing with the framework.

**Comment by josephmancuso** [comment]
No that's fine. Fix as many small issues as you find. What do you think of the framework though overall? (It of course needs improvement)

**Comment by ondoheer** [comment]
I haven't really had the time to read it full, but I wanted to build a simple app and see how it goes.
Orator is something I had never used before, so I'll have to read it's doc first. Maybe a Doc or another file where you can just sketch your ideas and choices would help, but maybe it's just me, since I'm trying to read /use it while dealing with RL.

**Comment by josephmancuso** [comment]
do you mean sketch my ideas and choices about what I want to framework to be? Or about Orator?
